cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'

cask '1password'
cask 'google-chrome'
cask 'hipchat'
cask 'slack'
cask 'steam'
cask 'tunnelbear'
cask 'vlc'
